# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_Ro1jZoOMRPQRSDBf4W5hP8Q5oxVQkV
"""

!rm -rf /content/drive

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
from pathlib import Path

# ============================================================
# Config
# ============================================================

BASE_OURS = Path("/content/drive/My Drive/waterstress/satellite")
BASE_GLORIA = Path("/content/drive/My Drive/waterstress/gloria_satellite")

OUTPUT = Path("/content/drive/My Drive/waterstress/output/gloria_period_density_scatter")
OUTPUT.mkdir(parents=True, exist_ok=True)

PERIODS = {
    "2013-2018": list(range(2013, 2019)),
    "2019-2024": list(range(2019, 2025)),
}

N_REGION = 164
N_SECTOR = 120
N_CROP_SECTOR = 14

# Python 0-indexed row numbers
ROW_WATER_STRESS = 390
ROW_BLUE_WATER_CONSUMPTION = 392

SECTOR_NAMES = [
    "Wheat",
    "Maize",
    "Cereals n.e.c.",
    "Leguminous & oil seeds",
    "Rice",
    "Vegetables, roots, tubers",
    "Sugar beet & cane",
    "Tobacco",
    "Fibre crops",
    "Crops n.e.c.",
    "Grapes",
    "Fruits & nuts",
    "Beverage crops",
    "Spices & aromatic",
]

# Plot settings
DENSITY_CMAP = "plasma"
FIG_DPI = 300

# ============================================================
# Helper functions
# ============================================================

def get_supply_cols(n_region=164, n_sector=120):
    """
    GLORIA TQ columns are interleaved as SUPPLY / USE.
    This extracts SUPPLY-side columns only.
    """
    supply_cols = []
    for c in range(n_region):
        for s in range(n_sector):
            col_idx = s + n_sector * c * 2
            supply_cols.append(col_idx)
    return np.array(supply_cols)

SUPPLY_COLS = get_supply_cols(N_REGION, N_SECTOR)


def load_ours(year):
    """
    Load our satellite account, expected shape after reshape: 164 × 120
    """
    path = BASE_OURS / f"satellite_{year}.npy"
    if not path.exists():
        print(f"[SKIP] Missing our file: {path}")
        return None

    arr = np.load(path).reshape(N_REGION, N_SECTOR)
    return arr


def load_gloria_ws(year):
    """
    Load GLORIA agriculture water stress row from TQ_{year}.csv,
    then extract supply-side columns and reshape to 164 × 120.
    """
    path = BASE_GLORIA / str(year) / f"TQ_{year}.csv"
    if not path.exists():
        print(f"[SKIP] Missing GLORIA file: {path}")
        return None

    rows_needed = [ROW_WATER_STRESS, ROW_BLUE_WATER_CONSUMPTION]

    gloria_rows = pd.read_csv(
        path,
        header=None,
        skiprows=lambda x: x not in rows_needed
    )

    if gloria_rows.shape[0] < 1:
        print(f"[SKIP] Could not read water-stress row for year {year}")
        return None

    gloria_ws = gloria_rows.iloc[0, SUPPLY_COLS].values.astype(float).reshape(N_REGION, N_SECTOR)
    return gloria_ws


def align_unit(ours, gloria_ws):
    """
    GLORIA is in million m3 H2Oeq.
    If our data is ~1e6 larger, convert ours from m3 to million m3.
    """
    ours_sum = ours[:, :N_CROP_SECTOR].sum()
    gloria_sum = gloria_ws[:, :N_CROP_SECTOR].sum()

    if gloria_sum == 0:
        return ours, 1, np.nan

    ratio = ours_sum / gloria_sum

    if ratio > 1e4:
        scale_factor = 1e6
    else:
        scale_factor = 1

    ours_aligned = ours / scale_factor
    return ours_aligned, scale_factor, ratio


def safe_corr(x, y, method="pearson", min_n=5):
    """
    Safe correlation with finite-value checking.
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    mask = np.isfinite(x) & np.isfinite(y)

    if mask.sum() < min_n:
        return np.nan

    x = x[mask]
    y = y[mask]

    if np.all(x == x[0]) or np.all(y == y[0]):
        return np.nan

    if method == "pearson":
        r, _ = stats.pearsonr(x, y)
    elif method == "spearman":
        r, _ = stats.spearmanr(x, y)
    else:
        raise ValueError("method must be 'pearson' or 'spearman'")

    return r


def prepare_density_colors_log(x, y):
    """
    Compute density in log10 space using gaussian_kde,
    then return x, y, normalized density sorted from low to high density.
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    mask = np.isfinite(x) & np.isfinite(y) & (x > 0) & (y > 0)
    x = x[mask]
    y = y[mask]

    if len(x) < 5:
        return x, y, None

    xy_log = np.vstack([np.log10(x), np.log10(y)])
    z = stats.gaussian_kde(xy_log)(xy_log)

    # sort so low-density points are drawn first, high-density points last
    idx = z.argsort()
    x = x[idx]
    y = y[idx]
    z = z[idx]

    # normalize to 0-1 for nicer colorbar
    z = (z - z.min()) / (z.max() - z.min() + 1e-12)

    return x, y, z


def load_period_mean(period_name, years):
    """
    Load all valid years in a period, align units year by year,
    keep first 14 crop-growing sectors, then compute period mean.
    """
    ours_list = []
    gloria_list = []
    used_years = []
    unit_records = []

    for year in years:
        ours = load_ours(year)
        gloria_ws = load_gloria_ws(year)

        if ours is None or gloria_ws is None:
            continue

        ours_mm3, scale_factor, ratio = align_unit(ours, gloria_ws)

        ours_crop = ours_mm3[:, :N_CROP_SECTOR]
        gloria_crop = gloria_ws[:, :N_CROP_SECTOR]

        ours_list.append(ours_crop)
        gloria_list.append(gloria_crop)
        used_years.append(year)

        unit_records.append({
            "period": period_name,
            "year": year,
            "scale_factor_applied_to_ours": scale_factor,
            "raw_unit_ratio_ours_over_gloria": ratio,
            "ours_total_first14_million_m3": ours_crop.sum(),
            "gloria_total_first14_million_m3": gloria_crop.sum(),
        })

    if len(ours_list) == 0:
        raise ValueError(f"No valid years found for period {period_name}")

    ours_mean = np.nanmean(np.stack(ours_list, axis=0), axis=0)
    gloria_mean = np.nanmean(np.stack(gloria_list, axis=0), axis=0)

    return ours_mean, gloria_mean, used_years, unit_records


# ============================================================
# Plot functions
# ============================================================

def plot_cell_level(ours_mean, gloria_mean, period_name, used_years, outdir):
    """
    Save cell-level density scatter.
    """
    ours_flat = ours_mean.flatten()
    gloria_flat = gloria_mean.flatten()

    mask = (
        (ours_flat > 0) &
        (gloria_flat > 0) &
        np.isfinite(ours_flat) &
        np.isfinite(gloria_flat)
    )

    x = gloria_flat[mask]
    y = ours_flat[mask]

    r = safe_corr(x, y, method="pearson")
    rho = safe_corr(x, y, method="spearman")

    x_plot, y_plot, z = prepare_density_colors_log(x, y)

    fig, ax = plt.subplots(figsize=(6.5, 5.5))

    if z is not None and len(x_plot) > 0:
        sc = ax.scatter(
            x_plot, y_plot,
            c=z,
            s=10,
            alpha=0.75,
            cmap=DENSITY_CMAP,
            edgecolors="none"
        )
        cbar = plt.colorbar(sc, ax=ax)
        cbar.set_label("Density of points")
    else:
        ax.scatter(x, y, s=10, alpha=0.75)

    ax.set_xscale("log")
    ax.set_yscale("log")

    if len(x_plot) > 0:
        lims = [
            min(x_plot.min(), y_plot.min()) * 0.5,
            max(x_plot.max(), y_plot.max()) * 2
        ]
        ax.plot(lims, lims, linestyle="--", color="red", alpha=0.7, label="1:1 line")
        ax.set_xlim(lims)
        ax.set_ylim(lims)
        ax.legend(frameon=False)

    ax.set_xlabel("GLORIA water stress, period mean (million m³)")
    ax.set_ylabel("CropWS water stress, period mean (million m³)")
    ax.set_title(f"{period_name} | Cell-level\nPearson r = {r:.3f}, Spearman ρ = {rho:.3f}")

    plt.tight_layout()

    png_path = outdir / f"{period_name.replace('-', '_')}_cell_level_density_scatter.png"
    pdf_path = outdir / f"{period_name.replace('-', '_')}_cell_level_density_scatter.pdf"

    plt.savefig(png_path, dpi=FIG_DPI, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")
    plt.close()

    return {
        "period": period_name,
        "level": "cell",
        "pearson_r": r,
        "spearman_rho": rho,
        "n_points": len(x),
        "used_years": ",".join(map(str, used_years)),
        "png": str(png_path),
        "pdf": str(pdf_path),
    }


def plot_country_level(ours_mean, gloria_mean, period_name, used_years, outdir):
    """
    Save country-level density scatter.
    """
    ours_country = ours_mean.sum(axis=1)
    gloria_country = gloria_mean.sum(axis=1)

    mask = (
        (ours_country > 0) &
        (gloria_country > 0) &
        np.isfinite(ours_country) &
        np.isfinite(gloria_country)
    )

    x = gloria_country[mask]
    y = ours_country[mask]

    r = safe_corr(x, y, method="pearson")
    rho = safe_corr(x, y, method="spearman")

    x_plot, y_plot, z = prepare_density_colors_log(x, y)

    fig, ax = plt.subplots(figsize=(6.5, 5.5))

    if z is not None and len(x_plot) > 0:
        sc = ax.scatter(
            x_plot, y_plot,
            c=z,
            s=35,
            alpha=0.85,
            cmap=DENSITY_CMAP,
            edgecolors="none"
        )
        cbar = plt.colorbar(sc, ax=ax)
        cbar.set_label("Density of points")
    else:
        ax.scatter(x, y, s=35, alpha=0.85)

    ax.set_xscale("log")
    ax.set_yscale("log")

    if len(x_plot) > 0:
        lims = [
            min(x_plot.min(), y_plot.min()) * 0.5,
            max(x_plot.max(), y_plot.max()) * 2
        ]
        ax.plot(lims, lims, linestyle="--", color="red", alpha=0.7, label="1:1 line")
        ax.set_xlim(lims)
        ax.set_ylim(lims)
        ax.legend(frameon=False)

    ax.set_xlabel("GLORIA country total, period mean (million m³)")
    ax.set_ylabel("CropWS country total, period mean (million m³)")
    ax.set_title(f"{period_name} | Country-level\nPearson r = {r:.3f}, Spearman ρ = {rho:.3f}")

    plt.tight_layout()

    png_path = outdir / f"{period_name.replace('-', '_')}_country_level_density_scatter.png"
    pdf_path = outdir / f"{period_name.replace('-', '_')}_country_level_density_scatter.pdf"

    plt.savefig(png_path, dpi=FIG_DPI, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")
    plt.close()

    return {
        "period": period_name,
        "level": "country",
        "pearson_r": r,
        "spearman_rho": rho,
        "n_points": len(x),
        "used_years": ",".join(map(str, used_years)),
        "png": str(png_path),
        "pdf": str(pdf_path),
    }


def plot_sector_level(ours_mean, gloria_mean, period_name, used_years, outdir):
    """
    Save sector-level bar comparison.
    """
    ours_sector = ours_mean.sum(axis=0)
    gloria_sector = gloria_mean.sum(axis=0)

    r = safe_corr(gloria_sector, ours_sector, method="pearson")
    rho = safe_corr(gloria_sector, ours_sector, method="spearman")

    x_pos = np.arange(N_CROP_SECTOR)
    width = 0.38

    fig, ax = plt.subplots(figsize=(9, 5.8))

    ax.bar(
        x_pos - width / 2,
        gloria_sector,
        width=width,
        alpha=0.75,
        label="GLORIA"
    )

    ax.bar(
        x_pos + width / 2,
        ours_sector,
        width=width,
        alpha=0.75,
        label="CropWS"
    )

    ax.set_xlabel("Crop-growing sector")
    ax.set_ylabel("Global sector total, period mean (million m³)")
    ax.set_title(f"{period_name} | Sector-level\nPearson r = {r:.3f}, Spearman ρ = {rho:.3f}")
    ax.set_xticks(x_pos)
    ax.set_xticklabels(SECTOR_NAMES, rotation=55, ha="right")
    ax.legend(frameon=False)

    plt.tight_layout()

    png_path = outdir / f"{period_name.replace('-', '_')}_sector_level_bar_comparison.png"
    pdf_path = outdir / f"{period_name.replace('-', '_')}_sector_level_bar_comparison.pdf"

    plt.savefig(png_path, dpi=FIG_DPI, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")
    plt.close()

    return {
        "period": period_name,
        "level": "sector",
        "pearson_r": r,
        "spearman_rho": rho,
        "n_points": N_CROP_SECTOR,
        "used_years": ",".join(map(str, used_years)),
        "png": str(png_path),
        "pdf": str(pdf_path),
    }


def plot_combined_panel(ours_mean, gloria_mean, period_name, used_years, outdir):
    """
    Save a combined 1x3 panel for convenience.
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 5.5))

    # --------------------------------------------------------
    # 1. Cell-level
    # --------------------------------------------------------
    ax = axes[0]
    ours_flat = ours_mean.flatten()
    gloria_flat = gloria_mean.flatten()

    mask = (
        (ours_flat > 0) &
        (gloria_flat > 0) &
        np.isfinite(ours_flat) &
        np.isfinite(gloria_flat)
    )

    x = gloria_flat[mask]
    y = ours_flat[mask]

    r = safe_corr(x, y, method="pearson")
    rho = safe_corr(x, y, method="spearman")

    x_plot, y_plot, z = prepare_density_colors_log(x, y)

    if z is not None and len(x_plot) > 0:
        sc = ax.scatter(
            x_plot, y_plot,
            c=z,
            s=10,
            alpha=0.75,
            cmap=DENSITY_CMAP,
            edgecolors="none"
        )
        cbar = plt.colorbar(sc, ax=ax)
        cbar.set_label("Density of points")

    ax.set_xscale("log")
    ax.set_yscale("log")
    if len(x_plot) > 0:
        lims = [
            min(x_plot.min(), y_plot.min()) * 0.5,
            max(x_plot.max(), y_plot.max()) * 2
        ]
        ax.plot(lims, lims, linestyle="--", color="red", alpha=0.7)
        ax.set_xlim(lims)
        ax.set_ylim(lims)

    ax.set_xlabel("GLORIA")
    ax.set_ylabel("CropWS")
    ax.set_title(f"Cell-level\nr={r:.3f}, ρ={rho:.3f}")

    # --------------------------------------------------------
    # 2. Country-level
    # --------------------------------------------------------
    ax = axes[1]
    ours_country = ours_mean.sum(axis=1)
    gloria_country = gloria_mean.sum(axis=1)

    mask = (
        (ours_country > 0) &
        (gloria_country > 0) &
        np.isfinite(ours_country) &
        np.isfinite(gloria_country)
    )

    x = gloria_country[mask]
    y = ours_country[mask]

    r = safe_corr(x, y, method="pearson")
    rho = safe_corr(x, y, method="spearman")

    x_plot, y_plot, z = prepare_density_colors_log(x, y)

    if z is not None and len(x_plot) > 0:
        sc = ax.scatter(
            x_plot, y_plot,
            c=z,
            s=30,
            alpha=0.85,
            cmap=DENSITY_CMAP,
            edgecolors="none"
        )
        cbar = plt.colorbar(sc, ax=ax)
        cbar.set_label("Density of points")

    ax.set_xscale("log")
    ax.set_yscale("log")
    if len(x_plot) > 0:
        lims = [
            min(x_plot.min(), y_plot.min()) * 0.5,
            max(x_plot.max(), y_plot.max()) * 2
        ]
        ax.plot(lims, lims, linestyle="--", color="red", alpha=0.7)
        ax.set_xlim(lims)
        ax.set_ylim(lims)

    ax.set_xlabel("GLORIA")
    ax.set_ylabel("CropWS")
    ax.set_title(f"Country-level\nr={r:.3f}, ρ={rho:.3f}")

    # --------------------------------------------------------
    # 3. Sector-level
    # --------------------------------------------------------
    ax = axes[2]
    ours_sector = ours_mean.sum(axis=0)
    gloria_sector = gloria_mean.sum(axis=0)

    r = safe_corr(gloria_sector, ours_sector, method="pearson")
    rho = safe_corr(gloria_sector, ours_sector, method="spearman")

    x_pos = np.arange(N_CROP_SECTOR)
    width = 0.38

    ax.bar(x_pos - width / 2, gloria_sector, width=width, alpha=0.75, label="GLORIA")
    ax.bar(x_pos + width / 2, ours_sector, width=width, alpha=0.75, label="CropWS")
    ax.set_xticks(x_pos)
    ax.set_xticklabels(SECTOR_NAMES, rotation=55, ha="right")
    ax.set_ylabel("Global sector total")
    ax.set_title(f"Sector-level\nr={r:.3f}, ρ={rho:.3f}")
    ax.legend(frameon=False)

    years_text = ", ".join(map(str, used_years))
    plt.suptitle(f"CropWS vs GLORIA | {period_name}\nPeriod mean based on years: {years_text}", fontsize=14, y=1.04)

    plt.tight_layout()

    png_path = outdir / f"{period_name.replace('-', '_')}_combined_panel.png"
    pdf_path = outdir / f"{period_name.replace('-', '_')}_combined_panel.pdf"

    plt.savefig(png_path, dpi=FIG_DPI, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")
    plt.close()

    return str(png_path), str(pdf_path)


# ============================================================
# Main run
# ============================================================

summary_records = []
unit_records_all = []

for period_name, years in PERIODS.items():
    print(f"\nProcessing period: {period_name}")

    period_dir = OUTPUT / period_name.replace("-", "_")
    period_dir.mkdir(parents=True, exist_ok=True)

    ours_mean, gloria_mean, used_years, unit_records = load_period_mean(period_name, years)
    unit_records_all.extend(unit_records)

    print(f"Used years: {used_years}")
    print(f"Ours total (period mean, first 14 sectors):   {ours_mean.sum():.4e}")
    print(f"GLORIA total (period mean, first 14 sectors): {gloria_mean.sum():.4e}")

    # Separate figures
    cell_info = plot_cell_level(ours_mean, gloria_mean, period_name, used_years, period_dir)
    country_info = plot_country_level(ours_mean, gloria_mean, period_name, used_years, period_dir)
    sector_info = plot_sector_level(ours_mean, gloria_mean, period_name, used_years, period_dir)

    summary_records.extend([cell_info, country_info, sector_info])

    # Combined panel
    combined_png, combined_pdf = plot_combined_panel(ours_mean, gloria_mean, period_name, used_years, period_dir)

    print(f"Saved combined panel: {combined_png}")
    print(f"Saved combined panel: {combined_pdf}")

# Save summary tables
summary_df = pd.DataFrame(summary_records)
summary_csv = OUTPUT / "period_plot_summary.csv"
summary_df.to_csv(summary_csv, index=False)

unit_df = pd.DataFrame(unit_records_all)
unit_csv = OUTPUT / "unit_check_by_year.csv"
unit_df.to_csv(unit_csv, index=False)

print("\nDone.")
print(f"Saved summary table: {summary_csv}")
print(f"Saved unit-check table: {unit_csv}")

pip install zarr

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import zipfile
import os

years = range(2016, 2017)

keep_patterns = ['T-Results', 'Y-Results', 'V-Results']

for year in years:
    zip_path = f'/content/drive/My Drive/waterstress/latest_releases/060/GLORIA_MRIO_Loop060_part_I_MRIOdatabase/GLORIA_MRIOs_60_{year}.zip'
    extract_path = f'/content/drive/My Drive/waterstress/gloria/{year}'

    os.makedirs(extract_path, exist_ok=True)

    print(f"Unzipping {year}...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print(f"Unzipped year {year}")

    print(f"Cleaning {year}...")
    deleted = 0
    for root, dirs, files in os.walk(extract_path):
        for filename in files:
            filepath = os.path.join(root, filename)

            has_results = any(p in filename for p in keep_patterns)
            is_markup001 = 'Markup001(full).csv' in filename

            if not (has_results and is_markup001):
                os.remove(filepath)
                deleted += 1

    print(f"✓ {year} done, deleted {deleted} files\n")

# import os
# import glob

# gloria_base = '/content/drive/My Drive/waterstress/gloria'

# keep_patterns = ['T-Results', 'Y-Results', 'V-Results']

# to_keep = []
# to_delete = []

# for year_folder in sorted(glob.glob(f'{gloria_base}/*')):
#     if not os.path.isdir(year_folder):
#         continue

#     year = os.path.basename(year_folder)
#     print(f"\n📁 Year {year}:")

#     for root, dirs, files in os.walk(year_folder):
#         for filename in files:
#             filepath = os.path.join(root, filename)
#             file_size = os.path.getsize(filepath) / (1024**3)  # GB

#             has_results = any(pattern in filename for pattern in keep_patterns)
#             is_markup001 = 'Markup001(full).csv' in filename

#             should_keep = has_results and is_markup001

#             if should_keep:
#                 to_keep.append(filepath)
#                 print(f"  ✓ KEEP: {filename} ({file_size:.2f} GB)")
#             else:
#                 to_delete.append((filepath, file_size))
#                 print(f"  ✗ DELETE: {filename} ({file_size:.2f} GB)")

# print("\n" + "="*60)
# print(f"📊 Summary:")
# print(f"   Files to KEEP: {len(to_keep)}")
# print(f"   Files to DELETE: {len(to_delete)}")
# total_delete_size = sum(size for _, size in to_delete)
# print(f"   Space to free: {total_delete_size:.2f} GB")

# deleted_count = 0
# freed_space = 0

# for filepath, size in to_delete:
#     try:
#         os.remove(filepath)
#         deleted_count += 1
#         freed_space += size
#         print(f"✗ Deleted: {os.path.basename(filepath)}")
#     except Exception as e:
#         print(f"⚠️ Failed: {filepath} - {e}")

# print(f"\n" + "="*60)
# print(f"✓ Done! Deleted {deleted_count} files, freed {freed_space:.2f} GB")

pip install zarr

# GLORIA MRIO Batch Processing (1990-2025)
# Convert SUT format to MRIO zarr format

import numpy as np
import zarr
import xarray as xr
import os
from tqdm import tqdm
import gc

BASE_INPUT_PATH = '/content/drive/My Drive/waterstress/gloria/'
OUTPUT_PATH = '/content/drive/My Drive/waterstress/gloria_mrio/'
YEAR_START = 2007
YEAR_END = 2008

os.makedirs(OUTPUT_PATH, exist_ok=True)

# GLORIA constants
N_REGIONS = 164
N_SECTORS = 120
N_FD_CATEGORIES = 6
MRIO_SIZE = N_REGIONS * N_SECTORS  # 19,680

def load_gloria_csv(filepath, dtype=np.float32):
    """Load GLORIA CSV file"""
    data = np.loadtxt(filepath, delimiter=',', dtype=dtype)
    return data


def sut_to_mrio_T(T_sut, dtype=np.float32):
    """T from SUT to MRIO format"""
    T_mrio = np.zeros((MRIO_SIZE, MRIO_SIZE), dtype=dtype)

    for c1 in range(N_REGIONS):
        for c2 in range(N_REGIONS):
            r1, r2 = c1 * N_SECTORS, (c1 + 1) * N_SECTORS
            c1_idx, c2_idx = c2 * N_SECTORS, (c2 + 1) * N_SECTORS
            sut_r1, sut_r2 = c1 * 240 + 120, c1 * 240 + 240
            sut_c1, sut_c2 = c2 * 240, c2 * 240 + 120
            T_mrio[r1:r2, c1_idx:c2_idx] = T_sut[sut_r1:sut_r2, sut_c1:sut_c2]

    return T_mrio


def sut_to_mrio_Y(Y_sut, dtype=np.float32):
    """Y from SUT to MRIO format"""
    Y_mrio = np.zeros((MRIO_SIZE, Y_sut.shape[1]), dtype=dtype)

    for c1 in range(N_REGIONS):
        r1, r2 = c1 * N_SECTORS, (c1 + 1) * N_SECTORS
        sut_r1, sut_r2 = c1 * 240 + 120, c1 * 240 + 240
        Y_mrio[r1:r2, :] = Y_sut[sut_r1:sut_r2, :]

    return Y_mrio


def sut_to_mrio_V(V_sut, dtype=np.float32):
    """V from SUT to MRIO format"""
    V_mrio = np.zeros((V_sut.shape[0], MRIO_SIZE), dtype=dtype)

    for c1 in range(N_REGIONS):
        mrio_c1, mrio_c2 = c1 * N_SECTORS, (c1 + 1) * N_SECTORS
        sut_c1, sut_c2 = c1 * 240, c1 * 240 + 120
        V_mrio[:, mrio_c1:mrio_c2] = V_sut[:, sut_c1:sut_c2]

    return V_mrio


def aggregate_Y_by_region(Y_mrio, dtype=np.float32):
    """Aggregate Y from 984 to 164 regions"""
    Y_agg = np.zeros((MRIO_SIZE, N_REGIONS), dtype=dtype)

    for r in range(N_REGIONS):
        col_start = r * N_FD_CATEGORIES
        col_end = col_start + N_FD_CATEGORIES
        Y_agg[:, r] = Y_mrio[:, col_start:col_end].sum(axis=1)

    return Y_agg


def process_year(year):
    """Process a single year"""
    input_path = os.path.join(BASE_INPUT_PATH, str(year))
    zarr_path = os.path.join(OUTPUT_PATH, f'{year}.zarr')

    # Check if already exists
    if os.path.exists(zarr_path):
        print(f"  ⏭️  {year}.zarr already exists, skipping")
        return True

    # Check if input folder exists
    if not os.path.exists(input_path):
        print(f"  ❌ Input folder not found: {input_path}")
        return False

    # Find Markup001 files
    files = os.listdir(input_path)
    t_file, y_file, v_file = None, None, None

    for f in files:
        if 'T-Results' in f and 'Markup001' in f:
            t_file = f
        elif 'Y-Results' in f and 'Markup001' in f:
            y_file = f
        elif 'V-Results' in f and 'Markup001' in f:
            v_file = f

    if not all([t_file, y_file, v_file]):
        print(f"  ❌ Missing Markup001 files for {year}")
        return False

    try:
        # Load raw data
        print(f"  Loading CSV files...")
        T_sut = load_gloria_csv(os.path.join(input_path, t_file))
        Y_sut = load_gloria_csv(os.path.join(input_path, y_file))
        V_sut = load_gloria_csv(os.path.join(input_path, v_file))

        # Convert to MRIO
        print(f"  Converting T matrix...")
        T_mrio = sut_to_mrio_T(T_sut)
        del T_sut
        gc.collect()

        print(f"  Converting Y matrix...")
        Y_mrio = sut_to_mrio_Y(Y_sut)
        del Y_sut
        gc.collect()

        print(f"  Converting V matrix...")
        V_mrio = sut_to_mrio_V(V_sut)
        del V_sut
        gc.collect()

        print(f"  Aggregating Y by region...")
        Y_region = aggregate_Y_by_region(Y_mrio)

        # Reshape for REX compatibility
        T_4d = T_mrio.reshape(N_REGIONS, N_SECTORS, N_REGIONS, N_SECTORS)
        Y_3d = Y_region.reshape(N_REGIONS, N_SECTORS, N_REGIONS)

        # Create Dataset
        ds = xr.Dataset({
            'T': xr.DataArray(
                T_4d,
                dims=['from_region', 'from_sector', 'to_region', 'to_sector'],
                attrs={'description': 'Transaction matrix', 'unit': '1000 USD'}
            ),
            'Y': xr.DataArray(
                Y_3d,
                dims=['from_region', 'from_sector', 'to_region'],
                attrs={'description': 'Final demand (aggregated by region)', 'unit': '1000 USD'}
            ),
            'V': xr.DataArray(
                V_mrio,
                dims=['value_added_category', 'region_sector'],
                attrs={'description': 'Value added', 'unit': '1000 USD'}
            ),
            'Y_full': xr.DataArray(
                Y_mrio,
                dims=['region_sector', 'final_demand'],
                attrs={'description': 'Final demand (full, 6 categories per region)', 'unit': '1000 USD'}
            ),
        })

        ds.attrs['source'] = 'GLORIA MRIO Database Release 060'
        ds.attrs['year'] = year
        ds.attrs['n_regions'] = N_REGIONS
        ds.attrs['n_sectors'] = N_SECTORS
        ds.attrs['valuation'] = 'Basic prices (Markup001)'

        encoding = {
            'T': {'chunks': (50, N_SECTORS, 50, N_SECTORS), 'dtype': 'float32'},
            'Y': {'chunks': (50, N_SECTORS, N_REGIONS), 'dtype': 'float32'},
            'V': {'chunks': (V_mrio.shape[0], 5000), 'dtype': 'float32'},
            'Y_full': {'chunks': (5000, Y_mrio.shape[1]), 'dtype': 'float32'},
        }

        # Save
        print(f"  Saving to zarr...")
        ds.to_zarr(zarr_path, mode='w', consolidated=True, encoding=encoding, zarr_format=2)

        # Verify
        ds_check = xr.open_zarr(zarr_path, consolidated=True)
        t_sum = float(ds_check['T'].sum())
        print(f"  ✅ Saved! T_sum={t_sum:.2e}")
        ds_check.close()

        # Clean up
        del T_mrio, Y_mrio, V_mrio, Y_region, T_4d, Y_3d, ds
        gc.collect()

        return True

    except Exception as e:
        print(f"  ❌ Error: {e}")
        gc.collect()
        return False


# Main loop
print("GLORIA MRIO Batch Processing")
print(f"Years: {YEAR_START} - {YEAR_END}")

success_count = 0
skip_count = 0
fail_count = 0

for year in range(YEAR_START, YEAR_END + 1):
    print(f"\n[{year}]")

    zarr_path = os.path.join(OUTPUT_PATH, f'{year}.zarr')
    if os.path.exists(zarr_path):
        print(f"  ⏭️  Already exists, skipping")
        skip_count += 1
        continue

    result = process_year(year)
    if result:
        success_count += 1
    else:
        fail_count += 1

print("\n" + "="*30)
print("Summary")
print("="*30)
print(f"  ✅ Success: {success_count}")
print(f"  ⏭️  Skipped: {skip_count}")
print(f"  ❌ Failed:  {fail_count}")

import zarr
import xarray as xr

print("zarr version:", zarr.__version__)
print("xarray version:", xr.__version__)

ds = xr.open_zarr('/content/drive/My Drive/waterstress/gloria_mrio/2007.zarr')
print("Variables:", list(ds.data_vars))

# 检查GLORIA原始数据
# z_2006 = zarr.open("/content/drive/My Drive/waterstress/gloria_mrio/2006.zarr", mode='r')
z_2007 = zarr.open("/content/drive/My Drive/waterstress/gloria_mrio/2007.zarr", mode='r')
# z_2008 = zarr.open("/content/drive/My Drive/waterstress/gloria_mrio/2008.zarr", mode='r')

# print("=== Z matrix sum ===")
# print(f"2006: {z_2006['T'][:].sum():.2e}")
print(f"2007: {z_2007['T'][:].sum():.2e}")
# print(f"2008: {z_2008['T'][:].sum():.2e}")

import zarr
import numpy as np

z_2007 = zarr.open("/content/drive/My Drive/waterstress/gloria_mrio/2007.zarr", mode='r')
T_2007 = z_2007['T'][:]

print(f"NaN count: {np.isnan(T_2007).sum()}")
print(f"Inf count: {np.isinf(T_2007).sum()}")
print(f"Total elements: {T_2007.size}")

nan_positions = np.argwhere(np.isnan(T_2007))
print(f"\nNaN positions (first 10):")
print(nan_positions[:10])

nan_rows = np.unique(nan_positions[:, 0])
nan_cols = np.unique(nan_positions[:, 1])
print(f"\nNaN in {len(nan_rows)} rows, {len(nan_cols)} cols")

import zarr
import numpy as np

z_2007 = zarr.open("/content/drive/My Drive/waterstress/gloria_mrio/2007.zarr", mode='r')
T_2007 = z_2007['T'][:]

print(f"NaN count: {np.isnan(T_2007).sum()}")
print(f"Inf count: {np.isinf(T_2007).sum()}")
print(f"Total elements: {T_2007.size}")

nan_positions = np.argwhere(np.isnan(T_2007))
print(f"\nNaN positions (first 10):")
print(nan_positions[:10])

nan_rows = np.unique(nan_positions[:, 0])
nan_cols = np.unique(nan_positions[:, 1])
print(f"\nNaN in {len(nan_rows)} rows, {len(nan_cols)} cols")

# import shutil
# import os

# OUTPUT_PATH = '/content/drive/My Drive/waterstress/gloria_mrio/'

# for year in range(1991, 2026):
#     zarr_path = os.path.join(OUTPUT_PATH, f'{year}.zarr')
#     if os.path.exists(zarr_path):
#         print(f"删除 {year}.zarr ...")
#         shutil.rmtree(zarr_path)
#         print(f"  ✅ 已删除")
#     else:
#         print(f"  ⏭️  {year}.zarr 不存在")

# print("\n完成！")

from pathlib import Path

def get_directory_size(path):
    """递归计算目录总大小"""
    total = 0
    for file in Path(path).rglob('*'):
        if file.is_file():
            total += file.stat().st_size
    return total

zarr_path = Path('/content/drive/My Drive/waterstress/gloria_mrio/2025.zarr')

if zarr_path.exists():
    size_in_gb = get_directory_size(zarr_path) / (1024**3)
    print(f"Zarr 目录大小: {size_in_gb:.2f} GB")

"""## satellite account extraction

"""

import zipfile
import os
import shutil
import glob

# === Settings ===
start_year = 1990
end_year = 2025

src_dir = '/content/drive/My Drive/waterstress/latest_releases/060/GLORIA_MRIO_Loop060_part_III_satelliteaccounts'
dst_base = '/content/drive/My Drive/waterstress/gloria_satellite'

for year in range(start_year, end_year + 1):
    print(f'Processing {year}...')

    zip_path = os.path.join(src_dir, f'GLORIA_SatelliteAccounts_060_{year}.zip')
    if not os.path.exists(zip_path):
        print(f'  ⚠ ZIP not found: {zip_path}')
        continue

    # Create output directory
    out_dir = os.path.join(dst_base, str(year))
    os.makedirs(out_dir, exist_ok=True)

    # Unzip to a temp folder first
    tmp_dir = os.path.join(dst_base, f'_tmp_{year}')
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(tmp_dir)

    # Find and rename TQ / YQ csvs
    for f in glob.glob(os.path.join(tmp_dir, '**', '*.csv'), recursive=True):
        fname = os.path.basename(f)
        if 'TQ-Results' in fname:
            shutil.move(f, os.path.join(out_dir, f'TQ_{year}.csv'))
            print(f'  ✓ TQ_{year}.csv')
        elif 'YQ-Results' in fname:
            shutil.move(f, os.path.join(out_dir, f'YQ_{year}.csv'))
            print(f'  ✓ YQ_{year}.csv')

    # Clean up temp
    shutil.rmtree(tmp_dir)

print('Done!')

import pandas as pd

path = "/content/drive/My Drive/waterstress/gloria_satellite/2018/TQ_2018.csv"

df_head = pd.read_csv(path, nrows=5)
print("Shape:", df_head.shape)
print("Columns (前10个):", df_head.columns[:10].tolist())
print("Dtypes:\n", df_head.dtypes[:10])
df_head.iloc[:, :10]

import numpy as np
import pandas as pd
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# 1. Load our data for 2002
# ============================================================
ours = np.load("/content/drive/My Drive/waterstress/satellite/satellite_2002.npy").reshape(164, 120)
print("=" * 70)
print("OUR DATA (satellite_2002.npy)")
print(f"  Shape: {ours.shape}")
print(f"  Non-zero elements: {np.count_nonzero(ours)}")
print(f"  Total sum: {ours.sum():.4e}")
print(f"  Sum of first 14 sectors: {ours[:, :14].sum():.4e}")

# ============================================================
# 2. Load GLORIA satellite for 2002
# ============================================================
# GLORIA TQ satellite: row 390 (0-indexed) = Agriculture water stress
# The CSV has 39360 columns (164 regions × 120 sectors × 2 supply-use)
# But we only need the first half (production/supply side = 19680 columns)

gloria_path = "/content/drive/My Drive/waterstress/gloria_satellite/2002/TQ_2002.csv"

# Since we can't access Google Drive, let's write the code for the user
# For now, demonstrate with a mock or explain the approach

print("\n" + "=" * 70)
print("CODE FOR GOOGLE COLAB (copy-paste this):")
print("=" * 70)

import numpy as np, pandas as pd

SAT_DIR    = "/content/drive/My Drive/waterstress/satellite"
GLORIA_DIR = "/content/drive/My Drive/waterstress/gloria_satellite"
WS_ROW = 390                      # GLORIA agriculture water stress 行 (0-indexed)
N_REGION, N_SECTOR, N_CROP = 164, 120, 14

supply_cols = np.array([s + 120 * c * 2 for c in range(N_REGION) for s in range(N_SECTOR)])
REGIONS = {"India": 72, "China": 33}

def load_ours(y):
    return np.load(f"{SAT_DIR}/satellite_{y}.npy").reshape(N_REGION, N_SECTOR)

def load_gloria(y):
    row = pd.read_csv(f"{GLORIA_DIR}/{y}/TQ_{y}.csv", header=None,
                      skiprows=lambda x: x != WS_ROW)
    return row.iloc[0, supply_cols].values.astype(float).reshape(N_REGION, N_SECTOR)

rec = {n: {"ours": {}, "gloria": {}} for n in REGIONS}
for y in range(1995, 2025):
    try:
        o, g = load_ours(y), load_gloria(y)
    except Exception as e:
        print(f"skip {y}: {e}"); continue
    for n, idx in REGIONS.items():
        rec[n]["ours"][y]   = o[idx, :N_CROP].sum()   # 你们：作物 water stress
        rec[n]["gloria"][y] = g[idx, :N_CROP].sum()   # GLORIA：作物 water stress

def growth(d, y0, y1):
    base   = np.mean([d[y] for y in y0 if y in d])
    recent = np.mean([d[y] for y in y1 if y in d])
    return (recent - base) / base * 100

print(f"{'Region':8}{'Source':9}{'1995–97 → 2022–24':>20}{'   1995 → 2024':>16}")
for n in REGIONS:
    for src in ["ours", "gloria"]:
        d = rec[n][src]
        g_mean   = growth(d, [1995,1996,1997], [2022,2023,2024])
        g_single = (d[2024]-d[1995])/d[1995]*100 if (1995 in d and 2024 in d) else float("nan")
        print(f"{n:8}{src:9}{g_mean:18.1f}%{g_single:15.1f}%")

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

# ============================================================
# 1. Load our data
# ============================================================
year = 2002  # Change this to compare different years

ours = np.load(f"/content/drive/My Drive/waterstress/satellite/satellite_{year}.npy").reshape(164, 120)

# ============================================================
# 2. Load GLORIA satellite - CORRECTED column extraction
# ============================================================
# GLORIA TQ has 39360 columns in SUPPLY-USE interleaved format:
#   col 0 = region 1, sector 1, SUPPLY
#   col 1 = region 1, sector 1, USE
#   col 2 = region 1, sector 2, SUPPLY
#   col 3 = region 1, sector 2, USE
#   ...
#   col 240 = region 2, sector 1, SUPPLY
#   col 241 = region 2, sector 1, USE
#   ...
#
# From gloria_laura.m:
#   c1_s1 = s1 + 120*(c1-1)*2   (1-indexed MATLAB)
# In 0-indexed Python:
#   col_idx = (s) + 120 * (c) * 2   where c=0..163, s=0..119

gloria_path = f"/content/drive/My Drive/waterstress/gloria_satellite/{year}/TQ_{year}.csv"

# Read water stress row (0-indexed row 390) and blue water consumption (row 392)
rows_needed = [390, 392]
gloria_rows = pd.read_csv(gloria_path, header=None,
                           skiprows=lambda x: x not in rows_needed)

print(f"GLORIA raw shape: {gloria_rows.shape}")  # should be (2, 39360)

# Build supply-side column indices following MATLAB logic
supply_cols = []
for c in range(164):       # region 0..163
    for s in range(120):   # sector 0..119
        col_idx = s + 120 * c * 2  # supply side column (0-indexed)
        supply_cols.append(col_idx)

supply_cols = np.array(supply_cols)

# Verify: first few should be 0,1,2,...,119 (region 1 supply cols)
# then 240,241,...,359 (region 2 supply cols)
print(f"First 5 supply cols: {supply_cols[:5]}")      # [0, 1, 2, 3, 4]
print(f"Cols 120-124: {supply_cols[120:125]}")         # [240, 241, 242, 243, 244]

gloria_ws = gloria_rows.iloc[0, supply_cols].values.astype(float).reshape(164, 120)
gloria_bwc = gloria_rows.iloc[1, supply_cols].values.astype(float).reshape(164, 120)

print(f"\nGLORIA Agriculture Water Stress (row 391):")
print(f"  Shape: {gloria_ws.shape}")
print(f"  Total sum: {gloria_ws.sum():.4e}")
print(f"  Unit: million m3 H2Oeq")

print(f"\nGLORIA Agriculture Blue Water Consumption (row 393):")
print(f"  Shape: {gloria_bwc.shape}")
print(f"  Total sum: {gloria_bwc.sum():.4e}")
print(f"  Unit: million m3 H2Oeq")

# ============================================================
# 3. Sanity check: top countries in GLORIA
# ============================================================
# GLORIA region labels (first few)
gloria_regions = {
    0: "Rest of Americas", 1: "Rest of Europe", 2: "Rest of Africa",
    3: "Rest of Asia-Pacific", 4: "Afghanistan", 5: "Angola",
    6: "Albania", 7: "UAE", 8: "Argentina", 9: "Armenia",
    10: "Australia", 11: "Austria", 12: "Azerbaijan", 13: "Burundi",
    14: "Belgium", 17: "Bangladesh", 18: "Bulgaria",
    33: "China", 50: "Egypt", 72: "India", 71: "Indonesia",
    74: "Iran", 75: "Iraq", 82: "Japan", 99: "Mexico",
    118: "Pakistan", 119: "Palestine", 122: "Philippines",
    130: "Russia", 144: "Syria", 148: "Thailand",
    151: "Turkey", 152: "Turkey", 154: "Ukraine",
    156: "USA", 157: "Uzbekistan",
}

print(f"\n{'='*70}")
print(f"SANITY CHECK: Top 10 countries by GLORIA water stress")
print(f"{'='*70}")
country_ws_gloria = gloria_ws[:, :14].sum(axis=1)
country_ws_ours = ours[:, :14].sum(axis=1)
top_gloria = np.argsort(country_ws_gloria)[::-1][:10]
for idx in top_gloria:
    name = gloria_regions.get(idx, f"Region {idx+1}")
    print(f"  Region {idx+1:>3} ({name:>20}): GLORIA={country_ws_gloria[idx]:.4e}, "
          f"Ours={country_ws_ours[idx]:.4e}")

print(f"\nTop 10 countries by OUR water stress:")
top_ours = np.argsort(country_ws_ours)[::-1][:10]
for idx in top_ours:
    name = gloria_regions.get(idx, f"Region {idx+1}")
    print(f"  Region {idx+1:>3} ({name:>20}): GLORIA={country_ws_gloria[idx]:.4e}, "
          f"Ours={country_ws_ours[idx]:.4e}")

# ============================================================
# 4. Share of first 14 sectors
# ============================================================
ws_total = gloria_ws.sum()
ws_first14 = gloria_ws[:, :14].sum()
ws_rest = gloria_ws[:, 14:].sum()

bwc_total = gloria_bwc.sum()
bwc_first14 = gloria_bwc[:, :14].sum()

print(f"\n{'='*70}")
print(f"GLORIA: Share of first 14 'Growing' sectors in total agriculture")
print(f"{'='*70}")
print(f"  Water Stress:")
print(f"    First 14 sectors: {ws_first14:.4e} ({ws_first14/ws_total*100:.1f}%)")
print(f"    Remaining 106 sectors: {ws_rest:.4e} ({ws_rest/ws_total*100:.1f}%)")
print(f"    Total: {ws_total:.4e}")
print(f"  Blue Water Consumption:")
print(f"    First 14 sectors: {bwc_first14:.4e} ({bwc_first14/bwc_total*100:.1f}%)")
print(f"    Remaining 106 sectors: {bwc_total-bwc_first14:.4e} ({(bwc_total-bwc_first14)/bwc_total*100:.1f}%)")

# Top non-crop sectors with water stress
print(f"\nTop 10 non-crop sectors (15-120) by water stress sum:")
sector_sums = gloria_ws[:, 14:].sum(axis=0)
top_idx = np.argsort(sector_sums)[::-1][:10]
for idx in top_idx:
    actual_sector = idx + 15  # 1-indexed sector number
    print(f"  Sector {actual_sector}: sum={sector_sums[idx]:.4e}")

# ============================================================
# 5. Unit alignment check
# ============================================================
print(f"\n{'='*70}")
print(f"UNIT CHECK")
print(f"{'='*70}")
print(f"  Our sum (first 14 sectors): {ours[:, :14].sum():.4e}")
print(f"  GLORIA WS sum (first 14 sectors): {ws_first14:.4e}")
ratio = ours[:, :14].sum() / ws_first14
print(f"  Ratio (ours / GLORIA): {ratio:.4f}")
print(f"  -> If ratio ~ 1e6, our unit is m3 vs GLORIA's million m3")

# ============================================================
# 6. Correlation analysis (first 14 sectors only)
# ============================================================
print(f"\n{'='*70}")
print(f"CORRELATION ANALYSIS: Our data vs GLORIA (first 14 sectors)")
print(f"{'='*70}")

# Convert our data to same unit as GLORIA (million m3)
if ratio > 1e4:
    scale_factor = 1e6  # our data in m3, GLORIA in million m3
    print(f"  Converting our data from m3 to million m3 (divide by 1e6)")
else:
    scale_factor = 1

ours_mm3 = ours / scale_factor  # now in million m3

# Flatten first 14 sectors for both
ours_flat = ours_mm3[:, :14].flatten()
gloria_flat = gloria_ws[:, :14].flatten()

# Overall correlation (all 164*14 = 2296 values)
mask = (ours_flat > 0) | (gloria_flat > 0)  # at least one non-zero
r_all, p_all = stats.pearsonr(ours_flat[mask], gloria_flat[mask])
r_spearman, p_sp = stats.spearmanr(ours_flat[mask], gloria_flat[mask])
print(f"\n  All non-zero cells (n={mask.sum()}):")
print(f"    Pearson r  = {r_all:.4f} (p={p_all:.2e})")
print(f"    Spearman ρ = {r_spearman:.4f} (p={p_sp:.2e})")

# Per-sector correlation
print(f"\n  Per-sector correlations (across 164 countries):")
sector_names = [
    "Growing wheat", "Growing maize", "Growing cereals n.e.c",
    "Growing leguminous & oil seeds", "Growing rice",
    "Growing vegetables, roots, tubers", "Growing sugar beet & cane",
    "Growing tobacco", "Growing fibre crops", "Growing crops n.e.c.",
    "Growing grapes", "Growing fruits & nuts",
    "Growing beverage crops", "Growing spices & aromatic"
]
print(f"  {'#':<3} {'Sector':<35} {'Pearson':>8} {'Spearman':>9} {'n':>5}")
print(f"  {'-'*62}")
for s in range(14):
    col_ours = ours_mm3[:, s]
    col_gloria = gloria_ws[:, s]
    mask_s = (col_ours > 0) | (col_gloria > 0)
    if mask_s.sum() > 5:
        r_s, _ = stats.pearsonr(col_ours[mask_s], col_gloria[mask_s])
        rho_s, _ = stats.spearmanr(col_ours[mask_s], col_gloria[mask_s])
        print(f"  {s+1:<3} {sector_names[s]:<35} {r_s:>8.4f} {rho_s:>9.4f} {mask_s.sum():>5}")
    else:
        print(f"  {s+1:<3} {sector_names[s]:<35} {'N/A':>8} {'N/A':>9} {mask_s.sum():>5}")

# Per-country correlation (top 20 by GLORIA)
print(f"\n  Per-country correlations (across 14 sectors):")
print(f"  Top 20 countries by GLORIA water stress:")
top_countries = np.argsort(country_ws_gloria)[::-1][:20]
for c in top_countries:
    row_ours = ours_mm3[c, :14]
    row_gloria = gloria_ws[c, :14]
    mask_c = (row_ours > 0) | (row_gloria > 0)
    name = gloria_regions.get(c, f"Region {c+1}")
    if mask_c.sum() > 3:
        r_c, _ = stats.pearsonr(row_ours[mask_c], row_gloria[mask_c])
        print(f"  {c+1:>3} {name:>20}: r={r_c:>7.4f}, "
              f"ours={row_ours.sum():.2e}, gloria={row_gloria.sum():.2e}")
    else:
        print(f"  {c+1:>3} {name:>20}: too few values")

# ============================================================
# 7. Scatter plots
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 7a. Overall scatter (cell-level)
ax = axes[0]
mask_plot = (ours_flat > 0) & (gloria_flat > 0)
if mask_plot.sum() > 0:
    ax.scatter(gloria_flat[mask_plot], ours_flat[mask_plot], alpha=0.3, s=10)
    ax.set_xscale('log')
    ax.set_yscale('log')
    lims = [max(gloria_flat[mask_plot].min(), ours_flat[mask_plot].min()) * 0.5,
            min(gloria_flat[mask_plot].max(), ours_flat[mask_plot].max()) * 2]
    ax.plot(lims, lims, 'r--', alpha=0.5, label='1:1 line')
    ax.legend()
ax.set_xlabel("GLORIA Agriculture Water Stress (million m³)")
ax.set_ylabel("Our Crop Water Stress (million m³)")
ax.set_title(f"Cell-level (r={r_all:.3f})")

# 7b. Country-level comparison
ax = axes[1]
co = ours_mm3[:, :14].sum(axis=1)
cg = gloria_ws[:, :14].sum(axis=1)
mask_c = (co > 0) & (cg > 0)
if mask_c.sum() > 2:
    r_country, _ = stats.pearsonr(co[mask_c], cg[mask_c])
    ax.scatter(cg[mask_c], co[mask_c], alpha=0.5, s=30)
    ax.set_xscale('log')
    ax.set_yscale('log')
    lims = [max(cg[mask_c].min(), co[mask_c].min()) * 0.5,
            min(cg[mask_c].max(), co[mask_c].max()) * 2]
    ax.plot(lims, lims, 'r--', alpha=0.5, label='1:1 line')
    ax.legend()
    ax.set_title(f"Country-level (r={r_country:.3f})")
else:
    r_country = float('nan')
    ax.set_title("Country-level (insufficient data)")
ax.set_xlabel("GLORIA (country total)")
ax.set_ylabel("Ours (country total)")

# 7c. Sector-level comparison
ax = axes[2]
so = ours_mm3[:, :14].sum(axis=0)
sg = gloria_ws[:, :14].sum(axis=0)
r_sector, _ = stats.pearsonr(so, sg)
x = np.arange(14)
ax.bar(x - 0.2, sg, alpha=0.6, label='GLORIA', width=0.4)
ax.bar(x + 0.2, so, alpha=0.6, label='Ours', width=0.4)
ax.set_xlabel("Sector")
ax.set_ylabel("Total water stress (million m³)")
ax.set_title(f"Sector-level (r={r_sector:.3f})")
ax.legend()
ax.set_xticks(x)
ax.set_xticklabels(range(1, 15), rotation=45)

plt.suptitle(f"Our Crop Water Stress vs GLORIA Agriculture Water Stress ({year})",
             fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig(f"comparison_vs_gloria_{year}.png", dpi=150, bbox_inches='tight')
plt.show()

# ============================================================
# 8. Multi-year comparison
# ============================================================
print(f"\n{'='*70}")
print(f"MULTI-YEAR CORRELATION SUMMARY")
print(f"{'='*70}")

results = []
for yr in range(1990, 2025):
    try:
        ours_yr = np.load(f"/content/drive/My Drive/waterstress/satellite/satellite_{yr}.npy").reshape(164, 120)
        gloria_yr_path = f"/content/drive/My Drive/waterstress/gloria_satellite/{yr}/TQ_{yr}.csv"

        gloria_yr_rows = pd.read_csv(gloria_yr_path, header=None,
                                      skiprows=lambda x: x not in [390])
        # Corrected: extract supply-side columns
        gloria_yr_ws = gloria_yr_rows.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

        # Convert units
        ours_yr_mm3 = ours_yr / scale_factor

        # Cell-level correlation (first 14 sectors)
        o = ours_yr_mm3[:, :14].flatten()
        g = gloria_yr_ws[:, :14].flatten()

        mask = (o > 0) | (g > 0)
        r, p = stats.pearsonr(o[mask], g[mask])
        rho, _ = stats.spearmanr(o[mask], g[mask])

        # Country-level
        co = ours_yr_mm3[:, :14].sum(axis=1)
        cg = gloria_yr_ws[:, :14].sum(axis=1)
        mc = (co > 0) & (cg > 0)
        r_c, _ = stats.pearsonr(co[mc], cg[mc])

        # Share of first 14 sectors in GLORIA
        total_ws = gloria_yr_ws.sum()
        share = gloria_yr_ws[:, :14].sum() / total_ws * 100 if total_ws > 0 else 0

        # Global total comparison
        ours_total = ours_yr_mm3[:, :14].sum()
        gloria_total = gloria_yr_ws[:, :14].sum()

        results.append({
            'year': yr,
            'pearson_cell': r,
            'spearman_cell': rho,
            'pearson_country': r_c,
            'gloria_first14_share_pct': share,
            'ours_total_Mm3': ours_total,
            'gloria_total_Mm3': gloria_total,
            'total_ratio': ours_total / gloria_total if gloria_total > 0 else np.nan
        })
        print(f"  {yr}: r_cell={r:.4f}, ρ_cell={rho:.4f}, r_country={r_c:.4f}, "
              f"GLORIA_14share={share:.1f}%, "
              f"totals: ours={ours_total:.2e} vs gloria={gloria_total:.2e}")
    except Exception as e:
        print(f"  {yr}: Error - {e}")

if results:
    df_results = pd.DataFrame(results)
    df_results.to_csv(f"comparison_results_summary.csv", index=False)
    print(f"\nSaved comparison_results_summary.csv")

    # Plot multi-year correlations
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    ax = axes[0]
    ax.plot(df_results['year'], df_results['pearson_cell'], 'o-', label='Cell-level Pearson')
    ax.plot(df_results['year'], df_results['spearman_cell'], 's-', label='Cell-level Spearman')
    ax.plot(df_results['year'], df_results['pearson_country'], '^-', label='Country-level Pearson')
    ax.set_xlabel("Year")
    ax.set_ylabel("Correlation coefficient")
    ax.set_title("Correlation with GLORIA over time")
    ax.legend()
    ax.grid(True, alpha=0.3)

    ax = axes[1]
    ax.plot(df_results['year'], df_results['ours_total_Mm3'], 'o-', label='Ours')
    ax.plot(df_results['year'], df_results['gloria_total_Mm3'], 's-', label='GLORIA')
    ax.set_xlabel("Year")
    ax.set_ylabel("Total water stress (million m³)")
    ax.set_title("Global total comparison")
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("comparison_multiyear.png", dpi=150, bbox_inches='tight')
    plt.show()

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

# ============================================================
# 1. Load our data
# ============================================================
year = 2023  # Change this to compare different years

ours = np.load(f"/content/drive/My Drive/waterstress/satellite/satellite_{year}.npy").reshape(164, 120)

# ============================================================
# 2. Load GLORIA satellite - CORRECTED column extraction
# ============================================================
# GLORIA TQ has 39360 columns in SUPPLY-USE interleaved format:
#   col 0 = region 1, sector 1, SUPPLY
#   col 1 = region 1, sector 1, USE
#   col 2 = region 1, sector 2, SUPPLY
#   col 3 = region 1, sector 2, USE
#   ...
#   col 240 = region 2, sector 1, SUPPLY
#   col 241 = region 2, sector 1, USE
#   ...
#
# From gloria_laura.m:
#   c1_s1 = s1 + 120*(c1-1)*2   (1-indexed MATLAB)
# In 0-indexed Python:
#   col_idx = (s) + 120 * (c) * 2   where c=0..163, s=0..119

gloria_path = f"/content/drive/My Drive/waterstress/gloria_satellite/{year}/TQ_{year}.csv"

# Read water stress row (0-indexed row 390) and blue water consumption (row 392)
rows_needed = [390, 392]
gloria_rows = pd.read_csv(gloria_path, header=None,
                           skiprows=lambda x: x not in rows_needed)

print(f"GLORIA raw shape: {gloria_rows.shape}")  # should be (2, 39360)

# Build supply-side column indices following MATLAB logic
supply_cols = []
for c in range(164):       # region 0..163
    for s in range(120):   # sector 0..119
        col_idx = s + 120 * c * 2  # supply side column (0-indexed)
        supply_cols.append(col_idx)

supply_cols = np.array(supply_cols)

# Verify: first few should be 0,1,2,...,119 (region 1 supply cols)
# then 240,241,...,359 (region 2 supply cols)
print(f"First 5 supply cols: {supply_cols[:5]}")      # [0, 1, 2, 3, 4]
print(f"Cols 120-124: {supply_cols[120:125]}")         # [240, 241, 242, 243, 244]

gloria_ws = gloria_rows.iloc[0, supply_cols].values.astype(float).reshape(164, 120)
gloria_bwc = gloria_rows.iloc[1, supply_cols].values.astype(float).reshape(164, 120)

print(f"\nGLORIA Agriculture Water Stress (row 391):")
print(f"  Shape: {gloria_ws.shape}")
print(f"  Total sum: {gloria_ws.sum():.4e}")
print(f"  Unit: million m3 H2Oeq")

print(f"\nGLORIA Agriculture Blue Water Consumption (row 393):")
print(f"  Shape: {gloria_bwc.shape}")
print(f"  Total sum: {gloria_bwc.sum():.4e}")
print(f"  Unit: million m3 H2Oeq")

# ============================================================
# 3. Sanity check: top countries in GLORIA
# ============================================================
# GLORIA region labels (first few)
gloria_regions = {
    0: "Rest of Americas", 1: "Rest of Europe", 2: "Rest of Africa",
    3: "Rest of Asia-Pacific", 4: "Afghanistan", 5: "Angola",
    6: "Albania", 7: "UAE", 8: "Argentina", 9: "Armenia",
    10: "Australia", 11: "Austria", 12: "Azerbaijan", 13: "Burundi",
    14: "Belgium", 17: "Bangladesh", 18: "Bulgaria",
    33: "China", 50: "Egypt", 72: "India", 71: "Indonesia",
    74: "Iran", 75: "Iraq", 82: "Japan", 99: "Mexico",
    118: "Pakistan", 119: "Palestine", 122: "Philippines",
    130: "Russia", 144: "Syria", 148: "Thailand",
    151: "Turkey", 152: "Turkey", 154: "Ukraine",
    156: "USA", 157: "Uzbekistan",
}

print(f"\n{'='*70}")
print(f"SANITY CHECK: Top 10 countries by GLORIA water stress")
print(f"{'='*70}")
country_ws_gloria = gloria_ws[:, :14].sum(axis=1)
country_ws_ours = ours[:, :14].sum(axis=1)
top_gloria = np.argsort(country_ws_gloria)[::-1][:10]
for idx in top_gloria:
    name = gloria_regions.get(idx, f"Region {idx+1}")
    print(f"  Region {idx+1:>3} ({name:>20}): GLORIA={country_ws_gloria[idx]:.4e}, "
          f"Ours={country_ws_ours[idx]:.4e}")

print(f"\nTop 10 countries by OUR water stress:")
top_ours = np.argsort(country_ws_ours)[::-1][:10]
for idx in top_ours:
    name = gloria_regions.get(idx, f"Region {idx+1}")
    print(f"  Region {idx+1:>3} ({name:>20}): GLORIA={country_ws_gloria[idx]:.4e}, "
          f"Ours={country_ws_ours[idx]:.4e}")

# ============================================================
# 4. Share of first 14 sectors
# ============================================================
ws_total = gloria_ws.sum()
ws_first14 = gloria_ws[:, :14].sum()
ws_rest = gloria_ws[:, 14:].sum()

bwc_total = gloria_bwc.sum()
bwc_first14 = gloria_bwc[:, :14].sum()

print(f"\n{'='*70}")
print(f"GLORIA: Share of first 14 'Growing' sectors in total agriculture")
print(f"{'='*70}")
print(f"  Water Stress:")
print(f"    First 14 sectors: {ws_first14:.4e} ({ws_first14/ws_total*100:.1f}%)")
print(f"    Remaining 106 sectors: {ws_rest:.4e} ({ws_rest/ws_total*100:.1f}%)")
print(f"    Total: {ws_total:.4e}")
print(f"  Blue Water Consumption:")
print(f"    First 14 sectors: {bwc_first14:.4e} ({bwc_first14/bwc_total*100:.1f}%)")
print(f"    Remaining 106 sectors: {bwc_total-bwc_first14:.4e} ({(bwc_total-bwc_first14)/bwc_total*100:.1f}%)")

# Top non-crop sectors with water stress
print(f"\nTop 10 non-crop sectors (15-120) by water stress sum:")
sector_sums = gloria_ws[:, 14:].sum(axis=0)
top_idx = np.argsort(sector_sums)[::-1][:10]
for idx in top_idx:
    actual_sector = idx + 15  # 1-indexed sector number
    print(f"  Sector {actual_sector}: sum={sector_sums[idx]:.4e}")

# ============================================================
# 5. Unit alignment check
# ============================================================
print(f"\n{'='*70}")
print(f"UNIT CHECK")
print(f"{'='*70}")
print(f"  Our sum (first 14 sectors): {ours[:, :14].sum():.4e}")
print(f"  GLORIA WS sum (first 14 sectors): {ws_first14:.4e}")
ratio = ours[:, :14].sum() / ws_first14
print(f"  Ratio (ours / GLORIA): {ratio:.4f}")
print(f"  -> If ratio ~ 1e6, our unit is m3 vs GLORIA's million m3")

# ============================================================
# 6. Correlation analysis (first 14 sectors only)
# ============================================================
print(f"\n{'='*70}")
print(f"CORRELATION ANALYSIS: Our data vs GLORIA (first 14 sectors)")
print(f"{'='*70}")

# Convert our data to same unit as GLORIA (million m3)
if ratio > 1e4:
    scale_factor = 1e6  # our data in m3, GLORIA in million m3
    print(f"  Converting our data from m3 to million m3 (divide by 1e6)")
else:
    scale_factor = 1

ours_mm3 = ours / scale_factor  # now in million m3

# Flatten first 14 sectors for both
ours_flat = ours_mm3[:, :14].flatten()
gloria_flat = gloria_ws[:, :14].flatten()

# Overall correlation (all 164*14 = 2296 values)
mask = (ours_flat > 0) | (gloria_flat > 0)  # at least one non-zero
r_all, p_all = stats.pearsonr(ours_flat[mask], gloria_flat[mask])
r_spearman, p_sp = stats.spearmanr(ours_flat[mask], gloria_flat[mask])
print(f"\n  All non-zero cells (n={mask.sum()}):")
print(f"    Pearson r  = {r_all:.4f} (p={p_all:.2e})")
print(f"    Spearman ρ = {r_spearman:.4f} (p={p_sp:.2e})")

# Per-sector correlation
print(f"\n  Per-sector correlations (across 164 countries):")
sector_names = [
    "Growing wheat", "Growing maize", "Growing cereals n.e.c",
    "Growing leguminous & oil seeds", "Growing rice",
    "Growing vegetables, roots, tubers", "Growing sugar beet & cane",
    "Growing tobacco", "Growing fibre crops", "Growing crops n.e.c.",
    "Growing grapes", "Growing fruits & nuts",
    "Growing beverage crops", "Growing spices & aromatic"
]
print(f"  {'#':<3} {'Sector':<35} {'Pearson':>8} {'Spearman':>9} {'n':>5}")
print(f"  {'-'*62}")
for s in range(14):
    col_ours = ours_mm3[:, s]
    col_gloria = gloria_ws[:, s]
    mask_s = (col_ours > 0) | (col_gloria > 0)
    if mask_s.sum() > 5:
        r_s, _ = stats.pearsonr(col_ours[mask_s], col_gloria[mask_s])
        rho_s, _ = stats.spearmanr(col_ours[mask_s], col_gloria[mask_s])
        print(f"  {s+1:<3} {sector_names[s]:<35} {r_s:>8.4f} {rho_s:>9.4f} {mask_s.sum():>5}")
    else:
        print(f"  {s+1:<3} {sector_names[s]:<35} {'N/A':>8} {'N/A':>9} {mask_s.sum():>5}")

# Per-country correlation (top 20 by GLORIA)
print(f"\n  Per-country correlations (across 14 sectors):")
print(f"  Top 20 countries by GLORIA water stress:")
top_countries = np.argsort(country_ws_gloria)[::-1][:20]
for c in top_countries:
    row_ours = ours_mm3[c, :14]
    row_gloria = gloria_ws[c, :14]
    mask_c = (row_ours > 0) | (row_gloria > 0)
    name = gloria_regions.get(c, f"Region {c+1}")
    if mask_c.sum() > 3:
        r_c, _ = stats.pearsonr(row_ours[mask_c], row_gloria[mask_c])
        print(f"  {c+1:>3} {name:>20}: r={r_c:>7.4f}, "
              f"ours={row_ours.sum():.2e}, gloria={row_gloria.sum():.2e}")
    else:
        print(f"  {c+1:>3} {name:>20}: too few values")

# ============================================================
# 7. Scatter plots
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 7a. Overall scatter (cell-level)
ax = axes[0]
mask_plot = (ours_flat > 0) & (gloria_flat > 0)
if mask_plot.sum() > 0:
    ax.scatter(gloria_flat[mask_plot], ours_flat[mask_plot], alpha=0.3, s=10)
    ax.set_xscale('log')
    ax.set_yscale('log')
    lims = [max(gloria_flat[mask_plot].min(), ours_flat[mask_plot].min()) * 0.5,
            min(gloria_flat[mask_plot].max(), ours_flat[mask_plot].max()) * 2]
    ax.plot(lims, lims, 'r--', alpha=0.5, label='1:1 line')
    ax.legend()
ax.set_xlabel("GLORIA Agriculture Water Stress (million m³)")
ax.set_ylabel("Our Crop Water Stress (million m³)")
ax.set_title(f"Cell-level (r={r_all:.3f})")

# 7b. Country-level comparison
ax = axes[1]
co = ours_mm3[:, :14].sum(axis=1)
cg = gloria_ws[:, :14].sum(axis=1)
mask_c = (co > 0) & (cg > 0)
if mask_c.sum() > 2:
    r_country, _ = stats.pearsonr(co[mask_c], cg[mask_c])
    ax.scatter(cg[mask_c], co[mask_c], alpha=0.5, s=30)
    ax.set_xscale('log')
    ax.set_yscale('log')
    lims = [max(cg[mask_c].min(), co[mask_c].min()) * 0.5,
            min(cg[mask_c].max(), co[mask_c].max()) * 2]
    ax.plot(lims, lims, 'r--', alpha=0.5, label='1:1 line')
    ax.legend()
    ax.set_title(f"Country-level (r={r_country:.3f})")
else:
    r_country = float('nan')
    ax.set_title("Country-level (insufficient data)")
ax.set_xlabel("GLORIA (country total)")
ax.set_ylabel("Ours (country total)")

# 7c. Sector-level comparison
ax = axes[2]
so = ours_mm3[:, :14].sum(axis=0)
sg = gloria_ws[:, :14].sum(axis=0)
r_sector, _ = stats.pearsonr(so, sg)
x = np.arange(14)
ax.bar(x - 0.2, sg, alpha=0.6, label='GLORIA', width=0.4)
ax.bar(x + 0.2, so, alpha=0.6, label='CropWS', width=0.4)
ax.set_xlabel("Sector")
ax.set_ylabel("Total water stress (million m³)")
ax.set_title(f"Sector-level (r={r_sector:.3f})")
ax.legend()
ax.set_xticks(x)
ax.set_xticklabels(range(1, 15), rotation=45)

plt.suptitle(f"Crop Water Stress vs GLORIA Agriculture Water Stress ({year})",
             fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig(f"comparison_vs_gloria_{year}.png", dpi=150, bbox_inches='tight')
plt.show()

"""
Update satellite .npy files: hybrid = our sectors 1-14 + GLORIA sectors 15-120
ALL in million m³ H2Oeq (matching GLORIA convention)

Years: 1990-2018
"""

import numpy as np
import pandas as pd
import os

# ============================================================
# 1. Build supply-side column indices (from gloria_laura.m)
# ============================================================
supply_cols = []
for c in range(164):
    for s in range(120):
        supply_cols.append(s + 120 * c * 2)
supply_cols = np.array(supply_cols)

# ============================================================
# 2. Process each year
# ============================================================
satellite_dir = "/content/drive/My Drive/waterstress/satellite"
gloria_dir = "/content/drive/My Drive/waterstress/gloria_satellite"
output_dir = "/content/drive/My Drive/waterstress/satellite_hybrid"

os.makedirs(output_dir, exist_ok=True)

WS_ROW = 390  # 0-indexed: row 391 = Agriculture water stress

for year in range(1990, 2026):
    ours_path = os.path.join(satellite_dir, f"satellite_{year}.npy")
    if not os.path.exists(ours_path):
        print(f"  {year}: our satellite not found, skipping")
        continue

    gloria_path = os.path.join(gloria_dir, str(year), f"TQ_{year}.csv")
    if not os.path.exists(gloria_path):
        print(f"  {year}: GLORIA TQ not found, skipping")
        continue

    # Load our data (in m³) and convert to million m³
    ours = np.load(ours_path).reshape(164, 120)
    ours_Mm3 = ours / 1e6

    # Load GLORIA (already in million m³)
    gloria_row = pd.read_csv(gloria_path, header=None,
                              skiprows=lambda x: x != WS_ROW)
    gloria_ws = gloria_row.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

    # Build hybrid: our first 14 (converted) + GLORIA rest (original)
    hybrid = np.zeros((164, 120))
    hybrid[:, :14] = ours_Mm3[:, :14]
    hybrid[:, 14:] = gloria_ws[:, 14:]

    # Save as (1, 19680)
    np.save(os.path.join(output_dir, f"satellite_{year}.npy"), hybrid.reshape(1, 164 * 120))

    # Summary
    ours_14 = hybrid[:, :14].sum()
    gloria_rest = hybrid[:, 14:].sum()
    total = hybrid.sum()

    print(f"  {year}: total={total:.4e} Mm³ | "
          f"ours(1-14)={ours_14:.4e} ({ours_14/total*100:.1f}%) | "
          f"GLORIA(15-120)={gloria_rest:.4e} ({gloria_rest/total*100:.1f}%)")

print(f"\nDone! All in million m³ H2Oeq. Saved to: {output_dir}")

import numpy as np

Q = np.load("/content/drive/My Drive/waterstress/satellite_hybrid/satellite_2016.npy")
print("Q shape:", Q.shape)

# 根据实际 shape 处理
if Q.ndim == 3:
    d_by_sector = Q[0].sum(axis=0)       # (164, 120) -> (120,)
elif Q.ndim == 2:
    d_by_sector = Q.sum(axis=0)           # 可能已经是 (164, 120) 没有外层
    if len(d_by_sector) == 164 * 120:
        d_by_sector = Q.reshape(-1, 120).sum(axis=0)

print("d_by_sector shape:", d_by_sector.shape)
print("d_by_sector:", d_by_sector)

target_sectors = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,
                  40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,63,67,68,71]
other_sectors = [s for s in range(120) if s not in target_sectors]

print(f"\nTarget sectors total: {d_by_sector[target_sectors].sum():.6e}")
print(f"Other sectors total:  {d_by_sector[other_sectors].sum():.6e}")

# 列出有非零值的非目标行业
print("\nNon-target sectors with non-zero water:")
for s in other_sectors:
    if d_by_sector[s] > 0:
        print(f"  Sector {s}: {d_by_sector[s]:.6e}")

if d_by_sector[other_sectors].sum() == 0:
    print("\n=> Remaining = 0 is correct: all water use is in target sectors.")

import numpy as np
import pandas as pd

satellite_dir = "/content/drive/My Drive/waterstress/satellite"
gloria_dir = "/content/drive/My Drive/waterstress/gloria_satellite"

supply_cols = []
for c in range(164):
    for s in range(120):
        supply_cols.append(s + 120 * c * 2)
supply_cols = np.array(supply_cols)

WS_ROW = 390

results = []

for year in range(1990, 2019):
    gloria_path = f"{gloria_dir}/{year}/TQ_{year}.csv"
    ours_path = f"{satellite_dir}/satellite_{year}.npy"

    try:
        # GLORIA original
        gloria_row = pd.read_csv(gloria_path, header=None,
                                  skiprows=lambda x: x != WS_ROW)
        gloria_ws = gloria_row.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

        gloria_1_14 = gloria_ws[:, :14].sum()
        gloria_15_120 = gloria_ws[:, 14:].sum()
        gloria_total = gloria_ws.sum()

        # Our data (raw, in m³)
        ours_raw = np.load(ours_path).reshape(164, 120)
        ours_1_14_m3 = ours_raw[:, :14].sum()
        ours_1_14_Mm3 = ours_1_14_m3 / 1e6

        results.append({
            'year': year,
            'gloria_1_14_Mm3': gloria_1_14,
            'gloria_15_120_Mm3': gloria_15_120,
            'gloria_total_Mm3': gloria_total,
            'gloria_1_14_pct': gloria_1_14 / gloria_total * 100,
            'ours_1_14_Mm3': ours_1_14_Mm3,
            'ours_1_14_m3': ours_1_14_m3,
            'ratio_ours_vs_gloria': ours_1_14_Mm3 / gloria_1_14 if gloria_1_14 != 0 else np.nan
        })
    except Exception as e:
        print(f"  {year}: error - {e}")

df = pd.DataFrame(results)
print("\n=== GLORIA original breakdown (all in Mm³ H2Oeq) ===")
print(df[['year', 'gloria_1_14_Mm3', 'gloria_15_120_Mm3', 'gloria_total_Mm3', 'gloria_1_14_pct']].to_string(index=False))

print("\n=== Your sectors 1-14 vs GLORIA sectors 1-14 ===")
print(df[['year', 'ours_1_14_Mm3', 'gloria_1_14_Mm3', 'ratio_ours_vs_gloria']].to_string(index=False))

print(f"\n=== Quick sanity check (year 2000) ===")
row2000 = df[df.year == 2000].iloc[0]
print(f"  GLORIA total:        {row2000.gloria_total_Mm3:.4e} Mm³")
print(f"  GLORIA total in km³: {row2000.gloria_total_Mm3 / 1e3:.1f} km³")
print(f"  Your 1-14 raw (m³):  {row2000.ours_1_14_m3:.4e}")
print(f"  Your 1-14 (Mm³):     {row2000.ours_1_14_Mm3:.4e}")
print(f"  Ratio ours/gloria:   {row2000.ratio_ours_vs_gloria:.2f}x")

import numpy as np
import pandas as pd

# 先定义 supply_cols
supply_cols = []
for c in range(164):
    for s in range(120):
        supply_cols.append(s + 120 * c * 2)
supply_cols = np.array(supply_cols)

gloria_row = pd.read_csv(f"/content/drive/My Drive/waterstress/gloria_satellite/2016/TQ_2016.csv",
                          header=None, skiprows=lambda x: x != 390)
vals = gloria_row.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

print(f"GLORIA sectors 14-119 non-zero cells: {(vals[:, 14:] != 0).sum()}")
print(f"GLORIA sectors 14-119 sum: {vals[:, 14:20].sum()}")

"""
Update satellite .npy files: hybrid = our sectors 1-14 + GLORIA sectors 15-120
Now includes BOTH Agriculture (row 391) and Non-agriculture (row 392) water stress
ALL in million m³ H2Oeq (matching GLORIA convention)
"""

import numpy as np
import pandas as pd
import os

# ============================================================
# 1. Build supply-side column indices
# ============================================================
supply_cols = []
for c in range(164):
    for s in range(120):
        supply_cols.append(s + 120 * c * 2)
supply_cols = np.array(supply_cols)

# ============================================================
# 2. Process each year
# ============================================================
satellite_dir = "/content/drive/My Drive/waterstress/satellite"
gloria_dir = "/content/drive/My Drive/waterstress/gloria_satellite"
output_dir = "/content/drive/My Drive/waterstress/satellite_hybrid_full"

os.makedirs(output_dir, exist_ok=True)

AG_ROW = 390      # 0-indexed: row 391 = Agriculture water stress
NON_AG_ROW = 391  # 0-indexed: row 392 = Non-agriculture water stress

for year in range(1990, 2026):
    ours_path = os.path.join(satellite_dir, f"satellite_{year}.npy")
    if not os.path.exists(ours_path):
        print(f"  {year}: our satellite not found, skipping")
        continue

    gloria_path = os.path.join(gloria_dir, str(year), f"TQ_{year}.csv")
    if not os.path.exists(gloria_path):
        print(f"  {year}: GLORIA TQ not found, skipping")
        continue

    # Load our data (in m³) and convert to million m³
    ours = np.load(ours_path).reshape(164, 120)
    ours_Mm3 = ours / 1e6

    # Load GLORIA Agriculture water stress (already in million m³)
    gloria_ag = pd.read_csv(gloria_path, header=None,
                             skiprows=lambda x: x != AG_ROW)
    gloria_ag_ws = gloria_ag.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

    # Load GLORIA Non-agriculture water stress (already in million m³)
    gloria_non_ag = pd.read_csv(gloria_path, header=None,
                                 skiprows=lambda x: x != NON_AG_ROW)
    gloria_non_ag_ws = gloria_non_ag.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

    # Build hybrid: our first 14 (converted) + GLORIA rest (ag + non-ag)
    hybrid = np.zeros((164, 120))
    hybrid[:, :14] = ours_Mm3[:, :14]
    hybrid[:, 14:] = gloria_ag_ws[:, 14:] + gloria_non_ag_ws[:, 14:]

    # Save as (1, 19680)
    np.save(os.path.join(output_dir, f"satellite_{year}.npy"), hybrid.reshape(1, 164 * 120))

    # Summary
    ours_14 = hybrid[:, :14].sum()
    gloria_rest = hybrid[:, 14:].sum()
    gloria_ag_rest = gloria_ag_ws[:, 14:].sum()
    gloria_non_ag_rest = gloria_non_ag_ws[:, 14:].sum()
    total = hybrid.sum()

    print(f"  {year}: total={total:.4e} Mm³ | "
          f"ours(1-14)={ours_14:.4e} ({ours_14/total*100:.1f}%) | "
          f"GLORIA(15-120)={gloria_rest:.4e} ({gloria_rest/total*100:.1f}%) "
          f"[ag={gloria_ag_rest:.4e}, non-ag={gloria_non_ag_rest:.4e}]")

print(f"\nDone! All in million m³ H2Oeq. Saved to: {output_dir}")

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill
from openpyxl.utils import get_column_letter

# ============================================================
# Build data from hybrid arrays (run after your existing code)
# ============================================================
rows = []
for year in range(1990, 2025):
    hybrid_path = os.path.join(output_dir, f"satellite_{year}.npy")
    if not os.path.exists(hybrid_path):
        continue
    hybrid = np.load(hybrid_path).reshape(164, 120)

    gloria_path = os.path.join(gloria_dir, str(year), f"TQ_{year}.csv")
    gloria_ag = pd.read_csv(gloria_path, header=None, skiprows=lambda x: x != AG_ROW)
    gloria_ag_ws = gloria_ag.iloc[0, supply_cols].values.astype(float).reshape(164, 120)
    gloria_non_ag = pd.read_csv(gloria_path, header=None, skiprows=lambda x: x != NON_AG_ROW)
    gloria_non_ag_ws = gloria_non_ag.iloc[0, supply_cols].values.astype(float).reshape(164, 120)

    total = hybrid.sum()
    ours_14 = hybrid[:, :14].sum()
    gloria_rest = hybrid[:, 14:].sum()
    ag_rest = gloria_ag_ws[:, 14:].sum()
    non_ag_rest = gloria_non_ag_ws[:, 14:].sum()

    rows.append({
        'Year': year,
        'Total': total,
        'Sectors 1–14': ours_14,
        'Share 1–14 (%)': ours_14 / total * 100,
        'Sectors 15–120': gloria_rest,
        'Share 15–120 (%)': gloria_rest / total * 100,
        'Crop': ag_rest,
        'Share crop (%)': ag_rest / gloria_rest * 100 if gloria_rest > 0 else 0,
        'Non-crop': non_ag_rest,
        'Share non-crop (%)': non_ag_rest / gloria_rest * 100 if gloria_rest > 0 else 0,
    })

df = pd.DataFrame(rows)

# ============================================================
# Create formatted Excel table
# ============================================================
wb = Workbook()
ws = wb.active
ws.title = "Table S1"

# --- Styles ---
header_font = Font(name='Arial', bold=True, size=10)
data_font = Font(name='Arial', size=10)
title_font = Font(name='Arial', bold=True, size=11)
note_font = Font(name='Arial', italic=True, size=9)
header_fill = PatternFill('solid', fgColor='D9E1F2')
thin_border = Border(
    bottom=Side(style='thin', color='000000')
)
thick_border = Border(
    bottom=Side(style='medium', color='000000')
)
center = Alignment(horizontal='center', vertical='center', wrap_text=True)
left = Alignment(horizontal='left', vertical='center')

# --- Title ---
ws.merge_cells('A1:J1')
ws['A1'] = 'Table S1. Hybrid water stress satellite account: detailed composition by year (million m³ H₂Oeq)'
ws['A1'].font = title_font
ws['A1'].alignment = left

ws.merge_cells('A2:J2')
ws['A2'] = ('Sectors 1–14 use authors\' characterization factors; sectors 15–120 use GLORIA MRIO '
            '(agriculture + non-agriculture water stress). All values in million m³ H₂Oeq.')
ws['A2'].font = note_font
ws['A2'].alignment = left

# --- Headers (two rows) ---
headers_r1 = ['', 'Total', 'Authors\' sectors (1–14)', '', 'GLORIA sectors (15–120)', '', '', '', '', '']
headers_r2 = ['Year', 'Water stress', 'Water stress', 'Share (%)',
              'Total', 'Share (%)', 'Crop', 'Crop share (%)',
              'Non-crop', 'Non-crop share (%)']

row_start = 4
# Top-level grouped headers
ws.merge_cells('C4:D4')
ws['C4'] = 'Authors\' sectors (1–14)'
ws.merge_cells('E4:J4')
ws['E4'] = 'GLORIA sectors (15–120)'

for col_idx in range(1, 11):
    cell = ws.cell(row=4, column=col_idx)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = center
    cell.border = thin_border

# Sub-headers
for col_idx, h in enumerate(headers_r2, 1):
    cell = ws.cell(row=5, column=col_idx)
    cell.value = h
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = center
    cell.border = thick_border

ws['A4'].value = ''
ws['B4'].value = ''

# --- Data rows ---
for i, row in df.iterrows():
    r = 6 + i
    ws.cell(r, 1, int(row['Year'])).font = data_font
    ws.cell(r, 1).alignment = center

    for col_idx, key, fmt in [
        (2, 'Total', '#,##0'),
        (3, 'Sectors 1–14', '#,##0'),
        (4, 'Share 1–14 (%)', '0.0'),
        (5, 'Sectors 15–120', '#,##0'),
        (6, 'Share 15–120 (%)', '0.0'),
        (7, 'Crop', '#,##0'),
        (8, 'Share crop (%)', '0.0'),
        (9, 'Non-crop', '#,##0'),
        (10, 'Share non-crop (%)', '0.0'),
    ]:
        cell = ws.cell(r, col_idx, round(row[key], 1))
        cell.font = data_font
        cell.number_format = fmt
        cell.alignment = center

# Bottom border on last data row
last_r = 6 + len(df) - 1
for col_idx in range(1, 11):
    ws.cell(last_r, col_idx).border = thick_border

# --- Column widths ---
widths = [6, 14, 14, 10, 12, 10, 12, 12, 12, 14]
for i, w in enumerate(widths, 1):
    ws.column_dimensions[get_column_letter(i)].width = w

# --- Note ---
note_r = last_r + 2
ws.merge_cells(f'A{note_r}:J{note_r}')
ws[f'A{note_r}'] = ('Note: "Crop" corresponds to GLORIA row 391 (Agriculture water stress); '
                     '"Non-crop" corresponds to row 392 (Non-agriculture water stress).')
ws[f'A{note_r}'].font = note_font

# --- Save ---
out_path = '/content/drive/My Drive/waterstress/Table_S1_water_stress.xlsx'
wb.save(out_path)
print(f"Saved to: {out_path}")

